[package]
name = "pocket-relay"
version = "0.1.0"
edition = "2021"
description = "Pocket Relay Server"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/PocketRelay/ServerRust"
readme = "README.md"
keywords = ["EA", "PocketRelay", "MassEffect"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
blaze-pk = "0.2.5"
