[workspace.package]
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/PocketRelay/ServerRust"

[workspace]
members = [
    ".",
    "core",
    "utils",
    "database",
    "servers/http",
    "servers/main",
    "servers/redirector",
]
exclude = ["tools"]

[workspace.dependencies]
# Tokio async runtime
tokio = { version = "1", features = ["full"] }

# Serde for serialization mostly in the HTTP server but also
# used elsewhere to do define custom serialization
serde = { version = "1", features = ["derive"] }

# Logging facade
log = "0.4"

# Blaze packet system 
blaze-pk = { version = "^0.6" }

# Resource embedding using debug-embed to always resolve relative 
# to the Cargo.toml file
rust-embed = { version = "6.4.2", features = ["debug-embed"] }

# Core application logic and shared state crate
core = { path = "core", package="pocket-relay-core", version="^0.1" }
# Isolated utilities crate
utils = { path = "utils", package="pocket-relay-utils", version = "^0.1"  }
# Isolated database crate
database = { path = "database", package="pocket-relay-database", version = "^0.1" }

# Blaze SSLv3 async TCPStream implementation
blaze-ssl-async = "^0.1"

[package]
name = "pocket-relay"
description = "Pocket Relay Server"
repository = "https://github.com/PocketRelay/ServerRust"
readme = "README.md"
keywords = ["EA", "PocketRelay", "MassEffect"]

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["database-sqlite"]
database-sqlite = ["core/database-sqlite"]
database-mysql = ["core/database-mysql"]

[dependencies]
core = { workspace = true }
utils = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }

# Individual servers
http-server = { path = "servers/http", package="pocket-relay-http-server", version = "^0.1" }
main-server = { path = "servers/main", package="pocket-relay-main-server", version = "^0.1" }
redirector-server = { path = "servers/redirector", package="pocket-relay-redirector-server", version = "^1" }
mitm-server = { path = "servers/mitm", package="pocket-relay-mitm-server", version = "^1" }

# .env file loader
dotenvy = "0.15.5"

# Library for obtaining the local IP address of the device
local-ip-address = "0.4.9"

# Logging provider 
[dependencies.log4rs]
version = "1.2.0"
default-features = false
features = [
    "gzip",
    "console_appender",
    "rolling_file_appender",
    "compound_policy",
    "fixed_window_roller",
    "size_trigger",
]


[profile.release]
strip = true
lto = true
