[workspace.package]
version = "0.1.2-alpha"
edition = "2021"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/PocketRelay/ServerRust"

[workspace]
members = [
    ".",
    "core",
    "utils",
    "database",
    "servers/http",
    "servers/main",
    "servers/redirector",
]
exclude = ["tools"]

[workspace.dependencies]
futures = "0.3.25"
tokio = { version = "1", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }

log = "0.4.17"

rust-embed = { version = "6.4.1", features = ["debug-embed"] }

core = { path = "core", package="pocket-relay-core", version="0.1.2-alpha" }
utils = { path = "utils", package="pocket-relay-utils", version = "0.1.0"  }
database = { path = "database", package="pocket-relay-database", version = "0.1.0" }

blaze-ssl-async = "0.1.1"

[workspace.dependencies.blaze-pk]
version = "0.6.0-alpha-6"
default-features = false
features = ["async", "blaze-ssl"]


[package]
name = "pocket-relay"
description = "Pocket Relay Server"
repository = "https://github.com/PocketRelay/ServerRust"
readme = "README.md"
keywords = ["EA", "PocketRelay", "MassEffect"]

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["database-sqlite"]
database-sqlite = ["core/database-sqlite"]
database-mysql = ["core/database-mysql"]

[dependencies]
core = { workspace = true }
utils = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }

http-server = { path = "servers/http", package="pocket-relay-http-server", version = "0.1.0" }
main-server = { path = "servers/main", package="pocket-relay-main-server", version = "0.1.0" }
redirector-server = { path = "servers/redirector", package="pocket-relay-redirector-server", version = "^1" }
mitm-server = { path = "servers/mitm", package="pocket-relay-mitm-server", version = "^1" }

dotenvy = "0.15.5"
local-ip-address = "0.4.9"

[dependencies.log4rs]
version = "1.2.0"
default-features = false
features = [
    "gzip",
    "console_appender",
    "rolling_file_appender",
    "compound_policy",
    "fixed_window_roller",
    "size_trigger",
]


[profile.release]
strip = true
lto = true
