[package]
name = "pocket-relay"
version = "0.1.0"
edition = "2021"
description = "Pocket Relay Server"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/PocketRelay/ServerRust"
readme = "README.md"
keywords = ["EA", "PocketRelay", "MassEffect"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
blaze-pk = { path = "../BlazePK", features = ["async"] }
actix-web = "4"
dotenvy = "0.15.5"
sea-orm = { version = "^0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }


log = "0.4.17"
env_logger = "0.9.1"
derive_more = "0.99.17"