[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    ".", 
    "core",
    "utils", 
    "database", 
    "servers/http", 
    "servers/main",
    "servers/redirector",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
blaze-pk = { version = "0.4.8", features = ["async", "blaze-ssl-async"] }
blaze-ssl-async = "0.1.1"
log = "0.4.17"

core = { path = "core" }
utils = { path = "utils" }
database = { path = "database" }


[package]
name = "pocket-relay"
description = "Pocket Relay Server"
repository = "https://github.com/PocketRelay/ServerRust"
readme = "README.md"
keywords = ["EA", "PocketRelay", "MassEffect"]

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
core = { workspace = true }
utils = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }

http-server = { path = "servers/http" }
main-server = { path = "servers/main" }
redirector-server = { path = "servers/redirector" }

dotenvy = "0.15.5"

[profile.release]
strip = true
lto = true
