[package]
name = "pocket-relay"
version = "0.1.0"
edition = "2021"
description = "Pocket Relay Server"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/PocketRelay/ServerRust"
readme = "README.md"
keywords = ["EA", "PocketRelay", "MassEffect"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [".", "migration"]

[dependencies]
# Async runtime
tokio = { version = "1", features = ["full"] }

# HTTP Server
actix-web = "4"
# HTTP Client
reqwest = { version = "0.11.12", features = ["json"] }

# Serialization and packets
blaze-pk = { version = "0.3.8", features = ["async"] }
serde = { version = "1.0", features = ["derive"] }
blaze-ssl = "0.1.2"

# Database dependencies
migration = { path = "migration" }
sea-orm = { version = "^0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }

# Logging
log = "0.4.17"
env_logger = "0.9.1"

# Utilities
dotenvy = "0.15.5"
derive_more = "0.99.17"
regex = "1"
rand = "0.8.5"
chrono = "0.4"

# Password hashing
rand_core = { version = "0.6", features = ["std"] }
argon2 = "0.4"
password-hash = "0.4.2"

# Resource / HTTP embedding
rust-embed={ version = "6.4.1", features = ["debug-embed"]}
mime_guess = "2.0.4"
