[package]
name = "pocket-relay"
version = "0.1.0"
edition = "2021"
description = "Pocket Relay Server"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/PocketRelay/ServerRust"
readme = "README.md"
keywords = ["EA", "PocketRelay", "MassEffect"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [".", "migration"]

[dependencies]
tokio = { version = "1", features = ["full"] }
blaze-pk = { path = "../BlazePK", features = ["async"] }
actix-web = "4"
dotenvy = "0.15.5"
sea-orm = { version = "^0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.57"

log = "0.4.17"
env_logger = "0.9.1"
derive_more = "0.99.17"

migration = { path = "migration" } # depends on your needs

argon2 = "0.4"
rand_core = { version = "0.6", features = ["std"] }
password-hash = "0.4.2"

rust-embed={ version = "6.4.1", features = ["debug-embed"]}
mime_guess = "2.0.4"
