[workspace.package]
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/PocketRelay/ServerRust"

[workspace]
members = [".", "database"]
exclude = ["tools"]

[workspace.dependencies]
# Tokio async runtime
tokio = { version = "1", features = ["full"] }

# Serde for serialization mostly in the HTTP server but also
# used elsewhere to do define custom serialization
serde = { version = "1", features = ["derive"] }

# Logging facade
log = "0.4"

# Blaze packet system 
blaze-pk = { version = "^0.6" }

# Resource embedding using debug-embed to always resolve relative 
# to the Cargo.toml file
rust-embed = { version = "6.4.2", features = ["debug-embed"] }

# Isolated database crate
database = { path = "database", package = "pocket-relay-database", version = "^0.1" }

# Blaze SSLv3 async TCPStream implementation
blaze-ssl-async = "^0.1"

rand_core = { version = "0.6", features = ["std"] }


[package]
name = "pocket-relay"
description = "Pocket Relay Server"
repository = "https://github.com/PocketRelay/ServerRust"
readme = "README.md"
keywords = ["EA", "PocketRelay", "MassEffect"]

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["database-sqlite"]
database-sqlite = ["database/sqlite"]
database-mysql = ["database/mysql"]

[dependencies]
tokio = { workspace = true }
log = { workspace = true }
blaze-pk = { workspace = true }
blaze-ssl-async = { workspace = true }
serde = { workspace = true }
database = { workspace = true }
futures-util = "0.3"
actix-web = { version = "4", default-features = false, features = ["macros"] }
actix-cors = "0.6.4"
rust-embed = { workspace = true }
mime_guess = "2.0.4"
argon2 = { version = "0.4" }
password-hash = { version = "0.4.2" }
rand_core = { workspace = true }

# .env file loader
dotenvy = "0.15.5"

# Library for obtaining the local IP address of the device
local-ip-address = "0.4.9"

# HTTP Client
[dependencies.reqwest]
version = "0.11.12"
default-features = false
features = ["json", "rustls-tls"]

[dependencies.regex]
version = "1"
default-features = false
features = ["std"]

# Logging provider 
[dependencies.log4rs]
version = "1.2.0"
default-features = false
features = [
    "gzip",
    "console_appender",
    "rolling_file_appender",
    "compound_policy",
    "fixed_window_roller",
    "size_trigger",
]


[profile.release]
strip = true
lto = true
