[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]

[workspace]
members = [
    ".",
    "core",
    "utils",
    "database",
    "servers/http",
    "servers/main",
    "servers/redirector",
    "tools"
]

[workspace.dependencies]
futures = "0.3.25"
tokio = { version = "1", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }

log = "0.4.17"

rust-embed = { version = "6.4.1", features = ["debug-embed"] }

core = { path = "core" }
utils = { path = "utils" }
database = { path = "database" }

blaze-ssl-async = "0.1.1"

[workspace.dependencies.blaze-pk]
version = "0.5.1"
default-features = false
features = ["async", "blaze-ssl"]


[package]
name = "pocket-relay"
description = "Pocket Relay Server"
repository = "https://github.com/PocketRelay/ServerRust"
readme = "README.md"
keywords = ["EA", "PocketRelay", "MassEffect"]

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["database-sqlite"]
database-sqlite = ["core/database-sqlite"]
database-mysql = ["core/database-mysql"]

[dependencies]
core = { workspace = true }
utils = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }

http-server = { path = "servers/http" }
main-server = { path = "servers/main" }
redirector-server = { path = "servers/redirector" }
mitm-server = { path = "servers/mitm" }

dotenvy = "0.15.5"

[profile.release]
strip = true
lto = true
