[package]
name = "http-server"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async runtime
tokio = { workspace = true }

# HTTP Server
actix-web = "4"

# Serialization and packets
serde =  { workspace = true }

core = { path = "../../core" }
database = { path = "../../database" }
utils = { path = "../../utils" }

# Logging
log = { workspace = true }

# Utilities
derive_more = "0.99.17"

# Resource / HTTP embedding
rust-embed={ version = "6.4.1", features = ["debug-embed"]}
mime_guess = "2.0.4"
futures = "0.3.25"
