//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "players")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub email: String,
    pub display_name: String,
    pub session_token: Option<String>,
    pub origin: bool,
    pub password: String,
    pub credits: u32,
    pub credits_spent: u32,
    pub games_played: u32,
    pub seconds_played: u32,
    pub inventory: String,
    pub csreward: u16,
    pub face_codes: Option<String>,
    pub new_item: Option<String>,
    pub completion: Option<String>,
    pub progress: Option<String>,
    pub cs_completion: Option<String>,
    pub cs_timestamps1: Option<String>,
    pub cs_timestamps2: Option<String>,
    pub cs_timestamps3: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
