[package]
name = "pocket-relay-database"
description = "Module for accessing the app database"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
sqlite = ["sea-orm/sqlx-sqlite", "sea-orm-migration/sqlx-sqlite"]
mysql = ["sea-orm/sqlx-mysql", "sea-orm-migration/sqlx-mysql"]

[dependencies]
tokio = { workspace = true }
async-std = { version = "^1", features = ["attributes", "tokio1"] }

log = { workspace = true }
utils = { workspace = true }
serde = { workspace = true }

chrono = "0.4"

[dependencies.sea-orm]
version = "^0"
features = ["runtime-tokio-rustls", "macros"]

[dependencies.sea-orm-migration]
version = "^0"
features = ["runtime-tokio-rustls"]
