[package]
name = "database"
version = "0.1.0"
edition = "2021"
description = "Module for accessing the app database"

[dependencies]
async-std = { version = "^1", features = ["attributes", "tokio1"] }

# Async runtime
tokio = { version = "1", features = ["full"] }

# Database dependencies
sea-orm = { version = "^0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }

# Logging
log = "0.4.17"


[dependencies.sea-orm-migration]
version = "^0.9.0"
features = [
    "runtime-tokio-rustls",
    "sqlx-sqlite"
  # Enable at least one `ASYNC_RUNTIME` and `DATABASE_DRIVER` feature if you want to run migration via CLI.
  # View the list of supported features at https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime.
  # e.g.
  # "runtime-tokio-rustls",  # `ASYNC_RUNTIME` feature
  # "sqlx-postgres",         # `DATABASE_DRIVER` feature
]
