version: "3"
services:
  pocket-relay:
    restart: unless-stopped
    image: jacobtread/pocket-relay:latest
    volumes:
      # Bind the server config to a local config.json file
      - ./config.json:/app/config.json
      # Binding the server data to a local data folder
      - ./data:/app/data
  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "8080:8080/tcp"
      - "8081:8081/udp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
