version: "3"
services:
  server:
    restart: unless-stopped
    container_name: pocket-relay
    image: jacobtread/pocket-relay:latest
    volumes:
      # Bind the server config to a local config.json file
      - ./config.json:/app/config.json
      # Binding the server data to a local data folder
      - ./data:/app/data
  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80/tcp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - server