[package]
name = "main-server"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async runtime
tokio = { workspace = true }

# Serialization and packets
blaze-pk = { workspace = true }
serde =  { workspace = true }
blaze-ssl-async = { workspace = true }

core = { path = "../../core" }
database = { path = "../../database" }
utils = { path = "../../utils" }

# Logging
log = { workspace = true }

derive_more = "0.99.17"

futures = "0.3.25"

rust-embed={ version = "6.4.1", features = ["debug-embed"]}
