[package]
name = "tools"
description = "Tooling for working creating files used by Pocket Relay"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

tokio = { workspace = true }
base64 = "0.13.1"

blaze-pk = { workspace = true }
flate2 = {version = "1.0.24", features = ["zlib"], default-features = false}