pub struct PlayerCharacterUpdate {
    pub kit_name: String,
    pub name: String,
    pub tint1: u16,
    pub tint2: u16,
    pub pattern: u16,
    pub pattern_color: u16,
    pub phong: u16,
    pub emissive: u16,
    pub skin_tone: u16,
    pub seconds_played: u32,
    pub timestamp_year: u32,
    pub timestamp_month: u32,
    pub timestamp_day: u32,
    pub timestamp_seconds: u32,
    pub powers: String,
    pub hotkeys: String,
    pub weapons: String,
    pub weapon_mods: String,
    pub deployed: bool,
    pub leveled_up: bool,
}
